add method == true in base.py
mind-inria/mri-nufft pull request #130
Opened 2024-06-12 14:19 UTC by Lenoush

add 

https://github.com/mind-inria/mri-nufft/blob/504426774146b209ea7fb2f67133022a04748dbb/src/mrinufft/operators/base.py#L344-L349

2024-06-12 14:33 UTC, paquiteau commented on src/mrinufft/operators/base.py
> +            return None
no need to move this

2024-06-12 14:34 UTC, paquiteau commented on src/mrinufft/operators/base.py
> +            method = "pipe"
you can remove the hasattr stuff, `method="pipe"` will use the `isinstance(method,str)` path, and will raise an error done the line if its not available for the backend.

2024-06-15 20:44 UTC, chaithyagr commented on src/mrinufft/operators/base.py
> +        if method is True:
```suggestion
        if method is True and self.backend is in ['tfnufft', 'gpunufft', 'torchkbnufft']:
```

As we dont support `pipe` for other classes.

2024-06-15 20:45 UTC, chaithyagr requested changes
Minor issues

2024-06-15 20:45 UTC, chaithyagr commented on src/mrinufft/operators/base.py
> +            If a bool, it will enable or disable the density compensation.
```suggestion
            If `True`, the method `pipe` is chosen as default estimation method, if 
            `backend` is `tfnufft`, `gpunufft` or `torchkbnufft`
```

2024-06-25 15:29 UTC, paquiteau commented on src/mrinufft/operators/base.py
> +            method = "pipe"
```suggestion
        if method is True:
            method = "pipe"
```

2024-06-25 15:30 UTC, paquiteau approved these changes

2024-06-26 07:44 UTC, merged