Adding a bunch of new examples
mind-inria/mri-nufft pull request #181
Opened 2024-08-20 14:31 UTC by chaithyagr

I have added following new examples:
1) Multiresolution learning with finufft backend without density compensation. This should be runnable on binder!
2) Learning for multicoil data.
3) Learning of straight line readouts (this is a learning example where the trajectory is parametrized.

2024-08-21 06:36 UTC, paquiteau requested changes
Nice work! I recommend adding more comments everywhere to help (rule of thumb: as many comments/explanations as lines of code). I know this is tedious, but I guess an LLM can help with that ;) 


Maybe we should think about putting these examples in a sub-gallery?

2024-08-21 06:36 UTC, paquiteau commented on examples/GPU/example_learn_samples_multicoil.py
> +        Path(os.getcwd()).parent.parent
you probably want to use `__file__` instead. You don't have the guarantee that you are running from the example directory.

2024-08-27 14:16 UTC, paquiteau reviewed
Awesome example ! 

I think we should add the equations explaining the autodiff aspects in the docs (`Explanation` rubric is perfect for that), and refer to it in the example.

2024-08-27 14:55 UTC, paquiteau requested changes

2024-08-27 14:55 UTC, paquiteau commented on examples/example_learn_samples_multires.py
> +    This example can run on a binder instance as it is purely CPU based backend (finufft).
```suggestion
    This example can run on a binder instance as it is purely CPU based backend (finufft), and is restricted to a 2D single coil toy case.
```

2024-08-28 07:14 UTC, chaithyagr commented on examples/GPU/example_learn_straight_line_readouts.py
I removed density compensation which is causing the issue. I will add it back...

2024-08-28 07:14 UTC, chaithyagr commented on examples/example_learn_samples_multires.py
> +    axs[1].set_title("Trajectory")
Ya possibly

2024-08-29 07:52 UTC, paquiteau requested changes

2024-08-29 07:52 UTC, paquiteau commented on examples/GPU/example_learn_samples_multicoil.py
> +            sample_points*2*np.pi,
This is a no-op, the trajectory is going to go through `proper_trajectory` for doing the scaling.

2024-08-29 07:52 UTC, paquiteau commented on examples/GPU/example_learn_samples_multicoil.py
>          self.sense_op.samples = self.trajectory.clone()
Same here

2024-08-29 13:06 UTC, paquiteau commented
LGTM !

2024-08-29 13:06 UTC, merged