Add support for fiNUFFT spread interpolate
mind-inria/mri-nufft pull request #224
Opened 2024-12-06 13:43 UTC by chaithyagr

This handles the final piece in puzzle, i.e. density compensation on CPU

This depends on #195 to go in and later https://github.com/flatironinstitute/finufft/pull/599 to be done and a release up.

2025-05-28 08:01 UTC, paquiteau commented on src/mrinufft/operators/interfaces/cufinufft.py
> +        plan.setpts(self._kx, self._ky, self._kz)
Seems redundant?

2025-05-28 08:04 UTC, paquiteau commented on src/mrinufft/operators/interfaces/utils/utils.py
> +    return nplus
I did not find any use of this function elsewhere. Is it really necessary ?

2025-06-04 14:43 UTC, chaithyagr commented on .github/workflows/test-ci.yml
> -          python -m pip install torchkbnufft
Well I anticipated this:
```
torchkbnufft = ["torchkbnufft", "cupy-cuda12x"]
torchkbnufft-cpu = ["torchkbnufft", "cupy-cuda12x"]
torchkbnufft-gpu = ["torchkbnufft", "cupy-cuda12x"]
```

Seeeee :P

2025-06-04 14:45 UTC, chaithyagr commented on src/mrinufft/operators/interfaces/utils/utils.py
> +    return nplus
Good catch, it was old obselete codes

2025-06-04 14:46 UTC, chaithyagr commented on src/mrinufft/operators/interfaces/cufinufft.py
> +        plan.setpts(self._kx, self._ky, self._kz)
Recommendation to have it better?

2025-06-04 14:46 UTC, chaithyagr commented on pyproject.toml
> +finufft = ["finufft==2.4.0rc1"]
Ya we can change it when its updated (can happen by the time this PR is updated)

2025-06-04 14:47 UTC, chaithyagr commented on .github/workflows/test-ci.yml
> +          pip install -e .[${{ matrix.backend }},autodiff]
Same as above :)

2025-06-04 14:49 UTC, chaithyagr commented on .github/workflows/test-ci.yml
> +
I dont think so? The tests would fail otherwise in CI I'm guessing. Atleast the installation of gpuNUFFT

2025-06-05 10:48 UTC, paquiteau commented
not quite a fan of the reduced accuracy for finufft, what changed it ? Also the CI reports strong mismatch. so the problem may go deeper...

2025-06-05 10:54 UTC, chaithyagr commented
I think it's a new "faster" spreader. We need to benchmark again to be sure of it. However i realised most of our tests are really very very strict, i looked at the results here and visually there's really no changes at all.

2025-06-06 08:08 UTC, chaithyagr commented
We need to do something about the tests being very strict, here is the actual images plots where we have maximum difference in output and input:

Most tests expects the error to be less than 1e-3 of absolute error 
For example for test_batch_adj_op:

Overlap of 
![image](https://github.com/user-attachments/assets/cf506e73-fb0c-45bf-8874-b75e4ddffb34)

Errors:
![image](https://github.com/user-attachments/assets/f50acd9d-0f85-47ba-858b-c2c7d67b7837)

Zoom in of errors:

![image](https://github.com/user-attachments/assets/f8904473-de6e-41e0-821f-b7a64b698399)



For now, I reduced most of the strictness, but only for finufft. We can open an issue to investigate what is happening, especially as it is happening only on CI server! Locally everything is running fine!

2025-06-06 08:22 UTC, paquiteau commented
What is the reference here ? maybe the "error" comes from the reference, and not finufft on the CI server ?

2025-06-12 06:41 UTC, chaithyagr commented
From run logs, the reference is finufft as shown below. The failing tests are more on batch and update tests, not reference. Its a bit bizzare issue, I must admit. Especially given it occurs only on CI server!
```
            backends: avail select
             stacked:  True False
   stacked-cufinufft:  True False
                bart: False False
           cufinufft: False False
             finufft:   REF   REF
            gpunufft: False False
              pynfft: False False
               numpy:  True False
         pynufft-cpu: False False
               sigpy:  True False
          tensorflow: False False
    torchkbnufft-cpu: False False
    torchkbnufft-gpu: False False
```

2025-06-13 06:52 UTC, chaithyagr commented
Its passing!!!!!! @paquiteau its passing!!!

2025-06-13 06:53 UTC, chaithyagr commented
Docs are here: https://github.com/mind-inria/mri-nufft/actions/runs/15612361826/artifacts/3315018984

2025-06-13 07:45 UTC, paquiteau requested changes
Some nitpicks, but that's very good :) Thank you for the hard work !

2025-06-13 07:45 UTC, paquiteau commented on src/mrinufft/operators/interfaces/cufinufft.py
> +        plan.setpts(self._kx, self._ky, self._kz)
well I don't understand why you need `_set_pts` and `_set_kxyz` for me `_set_pts(self, typ, samples)` should be enough. keeping an attribute `self._samples` would also be simpler (IMO) than `_kx,_ky,_kz`.

2025-06-13 07:45 UTC, paquiteau commented on src/mrinufft/operators/interfaces/cufinufft.py
> +        grid_op = MRICufiNUFFT(
Since this is a classmethod, use `cls` instead of the backend name. Ultimately this could be refactorized between all backend that supports "pipe" density (with an extra attention to the cupy/numpy array interface)

2025-06-13 07:45 UTC, paquiteau commented on src/mrinufft/operators/interfaces/finufft.py
> +        return density_comp.squeeze()
same comment as for cufinufft, use `cls`, maybe consider refactoring

2025-06-13 08:43 UTC, chaithyagr commented on src/mrinufft/operators/interfaces/finufft.py
> +        return density_comp.squeeze()
Ill use cls, but what do you mean by refactoring?

2025-06-13 11:39 UTC, paquiteau commented on src/mrinufft/operators/interfaces/finufft.py
> +        return density_comp.squeeze()
have a single pipe function in the code base (and not 3 different implementation for finufft, cufinufft, gpunufft). Maybe a mixin class could do the trick.

2025-06-13 12:12 UTC, chaithyagr commented on src/mrinufft/operators/interfaces/finufft.py
> +        return density_comp.squeeze()
Ahh yes, handling it in #231 for it would be ideal.. i don't want to burden this PR

2025-06-13 12:13 UTC, chaithyagr commented on src/mrinufft/operators/interfaces/finufft.py
> +        return density_comp.squeeze()
Ahh yes, handling it in #231 for it would be ideal.. i don't want to burden this PR

2025-06-16 07:47 UTC, chaithyagr commented
> well I don't understand why you need _set_pts and _set_kxyz for me _set_pts(self, typ, samples) should be enough. keeping an attribute self._samples would also be simpler (IMO) than _kx,_ky,_kz.

I honestly really dont remember why i did this :P  . Its been sooo long.

2025-06-16 07:51 UTC, chaithyagr commented
Updated it. Hopefully we can merge this today!

2025-06-16 13:21 UTC, paquiteau approved these changes
LGTM

Let's keep in mind this accuracy issue for later

2025-06-16 13:28 UTC, merged

2025-06-26 12:36 UTC, kborsos commented
Thank you all for the really wonderful work!!! We're really excited to try this out, are there plans to package this commit into a new release in the near future? I see the docs have been updated but the density compensation is still not available for cufinufft in v1.2.1. 

Edit: Nevermind I see this will be part of the 1.3 release, looking forward to trying it out soon - thanks again!

2025-06-26 14:23 UTC, chaithyagr commented
Hey @kborsos , feel free to use `pip install git+https://github.com/mind-inria/mri-nufft#egg=mri-nufft[cufinufft]` to already use it. We are waiting a release from the cufinufft folks (which is currently a pre-release) to make our release, to avoid issues for users. 
However, the above command works just fine!

2025-06-27 09:10 UTC, kborsos commented
Awesome, I have installed it now will start playing around with it. Thank you!